export const REQUESTED_PRODUCTS = 'REQUESTED_PRODUCTS';
export const REQUESTED_PRODUCTS_SUCCEEDED = 'REQUESTED_PRODUCTS_SUCCEEDED';
export const REQUESTED_PRODUCTS_FAILED = 'REQUESTED_PRODUCTS_FAILED';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';
